import { Lexend } from "next/font/google";
import { Moo_Lah_Lah } from "next/font/google";
// import "./globals.css";
import Link from "next/link";

export const lexend = Lexend({
  weight: "400",
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const mooLahLah = Moo_Lah_Lah({
  weight: "400",
  subsets: ["latin-ext"],
  variable: "--font-mooLahLah",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link href="/new">New Post</Link>
        {children}
      </body>
    </html>
  );
}
